CREATE TABLE "COMMUTE" (
	"COMMUTE_NO"	NUMBER	PRIMARY KEY	NOT NULL,
	"IN_DTIME"	TIMESTAMP		NULL,
	"OUT_DTIME"	TIMESTAMP		NULL,
	"LATE_YN"	VARCHAR2(1)	CHECK(LATE_YN IN('Y','N')),
	"STATUS"	VARCHAR2(45)	 CHECK(STATUS IN('10','20','30','40')),
	"OVERTIME" NUMBER NULL,
	"WORKINGDAY" DATE DEFAULT TO_TIMESTAMP_TZ(TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AT TIME ZONE 'Asia/Seoul',
	"EMP_NO" VARCHAR2(15) NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);


DROP TABLE COMMUTE;

CREATE TABLE "SCHEDULE" (
	"SCHEDULE_NO"	NUMBER	PRIMARY KEY	NOT NULL,
	"SKD_TITLE"	VARCHAR2(30)		NOT NULL,
	"SKD_CONTENT"	VARCHAR2(100)		NOT NULL,
	"SKD_START"	DATE		NOT NULL,
	"SKD_END"	DATE		NOT NULL,
	"SKD_TYPE_CD"	VARCHAR2(2)	CHECK(SKD_TYPE_CD IN('01','02'))	NOT NULL,
	"DEPT_CODE"	VARCHAR2(10)		NULL,
	"EMP_NO" VARCHAR2(15) NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
	"CATEGORY"	VARCHAR2(2)	CHECK(CATEGORY IN('10','20','99'))	NOT NULL
);


DROP TABLE SCHEDULE ;

SELECT * FROM schedule;
SELECT * FROM commute;
SELECT * FROM EMPLOYEE;
SELECT * FROM APPROVAL;

DELETE FROM COMMUTE;
ALTER TABLE  COMMUTE DROP CONSTRAINT UQ_WORKING;
ALTER TABLE COMMUTE ADD CONSTRAINTS UQ_WORKING UNIQUE(WORKINGDAY,EMP_NO);

ALTER TABLE COMMUTE MODIFY WORKINGDAY DATE;
ALTER TABLE COMMUTE MODIFY WORKINGDAY DATE DEFAULT SYSDATE;
ALTER TABLE COMMUTE ADD (WORKINGHOURS NUMBER(19, 0));
ALTER TABLE SCHEDULE ADD (SKD_IMPT VARCHAR2(30));
ALTER TABLE SCHEDULE ADD (REG_DTIME VARCHAR2(15));
ALTER TABLE SCHEDULE ADD (MOD_DTIME VARCHAR2(15));

 SELECT NVL(SUM(OVERTIME), 0) AS TOTAL_OVERTIME
  FROM COMMUTE
  WHERE EMP_NO = 'ATO_2' AND WORKINGDAY BETWEEN TO_DATE('2024.01.14', 'YYYY-MM-DD') AND TO_DATE('2024.01.20', 'YYYY-MM-DD');

 SELECT NVL(SUM(OVERTIME), 0) 
    FROM COMMUTE 
    WHERE TO_CHAR(WORKINGDAY, 'YYYY-MM') = '2024-01'
    AND EMP_NO = 'ATO_2';