CREATE TABLE "COMMUTE" (
	"COMMUTE_NO"	NUMBER	PRIMARY KEY	NOT NULL,
	"IN_DTIME"	TIMESTAMP		NULL,
	"OUT_DTIME"	TIMESTAMP		NULL,
	"LATE_YN"	VARCHAR2(1)	CHECK(LATE_YN IN('Y','N')),
	"STATUS"	VARCHAR2(45)	 CHECK(STATUS IN('10','20','30','40')),
	"OVERTIME" NUMBER NULL,
	"WORKINGDAY" DATE DEFAULT TO_TIMESTAMP_TZ(TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AT TIME ZONE 'Asia/Seoul',
	"EMP_NO" VARCHAR2(15) NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);

ALTER TABLE 

DROP TABLE COMMUTE;

CREATE TABLE "SCHEDULE" (
	"SCHEDULE_NO"	NUMBER	PRIMARY KEY	NOT NULL,
	"SKD_TITLE"	VARCHAR2(30)		NOT NULL,
	"SKD_CONTENT"	VARCHAR2(100)		NOT NULL,
	"SKD_START"	DATE		NOT NULL,
	"SKD_END"	DATE		NOT NULL,
	"SKD_TYPE_CD"	VARCHAR2(2)	CHECK(SKD_TYPE_CD IN('01','02'))	NOT NULL,
	"DEPT_CODE"	VARCHAR2(10)		NULL,
	"EMP_NO" VARCHAR2(15) NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
	"CATEGORY"	VARCHAR2(2)	CHECK(CATEGORY IN('10','20','99'))	NOT NULL
);


ALTER TABLE SCHEDULE MODIFY SKD_START VARCHAR2(45);
ALTER TABLE SCHEDULE MODIFY SKD_END VARCHAR2(45);

ALTER TABLE COMMUTE  MODIFY IN_DTIME TIMESTAMP DEFAULT TO_TIMESTAMP_TZ(TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AT TIME ZONE 'Asia/Seoul';
ALTER TABLE COMMUTE  MODIFY OUT_DTIME TIMESTAMP DEFAULT TO_TIMESTAMP_TZ(TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AT TIME ZONE 'Asia/Seoul';

-- 시퀀스 생성
CREATE SEQUENCE SEQ_SCHEDULE_NO
INCREMENT BY 1 --증감숫자 1
START WITH 1 --시작숫자 1
MINVALUE 1 --최소값 1
MAXVALUE 1000 --최대값 1000
NOCYCLE --순한하지않음
NOCACHE; 

DROP TABLE SCHEDULE ;

SELECT * FROM schedule;

SELECT min(IN_DTIME)
		  , max(OUT_DTIME)
   FROM COMMUTE 
WHERE EMP_NO ='ATO_2' 
     AND TRUNC(WORKINGDAY)=TO_DATE('24-01-18');
  ORDER BY COMMUTE_NO  ;
    
SELECT * FROM commute WHERE EMP_NO ='ATO_2' AND TRUNC(WORKINGDAY)=TO_DATE('24-01-18'); AND IN_DTIME IS NOT NULL
;
SELECT * FROM commute;

SELECT * FROM EMPLOYEE;
SELECT * FROM APPROVAL;
SELECT * FROM ATO_JOB;

DELETE FROM COMMUTE;
ALTER TABLE  COMMUTE DROP CONSTRAINT UQ_WORKING;
ALTER TABLE COMMUTE ADD CONSTRAINTS UQ_WORKING UNIQUE(WORKINGDAY,EMP_NO);

ALTER TABLE COMMUTE MODIFY WORKINGDAY DATE;
ALTER TABLE COMMUTE MODIFY WORKINGDAY DATE DEFAULT SYSDATE;
ALTER TABLE COMMUTE ADD (WORKINGHOURS NUMBER(19, 0));
ALTER TABLE SCHEDULE ADD (SKD_IMPT VARCHAR2(30));
ALTER TABLE SCHEDULE ADD (REG_DTIME VARCHAR2(15));
ALTER TABLE SCHEDULE ADD (MOD_DTIME VARCHAR2(15));

 SELECT NVL(SUM(OVERTIME), 0) AS TOTAL_OVERTIME
  FROM COMMUTE
  WHERE EMP_NO = 'ATO_2' AND WORKINGDAY BETWEEN TO_DATE('2024.01.14', 'YYYY-MM-DD') AND TO_DATE('2024.01.20', 'YYYY-MM-DD');
 SELECT NVL(SUM(workingHours),0) 
    FROM COMMUTE 
    WHERE EMP_NO  ='ATO_2'
    AND WORKINGDAY  BETWEEN '2024-01-22'AND TO_DATE('2024-01-27') + 0.5;
   
 SELECT NVL(SUM(OVERTIME), 0) 
    FROM COMMUTE 
    WHERE TO_CHAR(WORKINGDAY, 'YYYY-MM') = '2024-01'
    AND EMP_NO = 'ATO_2';
    
  SELECT * FROM COMMUTE WHERE EMP_NO ='ATO_2'AND
		TRUNC(WORKINGDAY)>TO_DATE('202-01-20')
		AND IN_DTIME IS NOT NULL;
   
   
   
 INSERT INTO APPROVAL (APPSEQ, APPWRITEDATE, APPCHECK, APPKINDS, EMP_NO)
VALUES (app_seq.NEXTVAL, SYSDATE, '결재완료', 'D3', 'ATO_2');


SELECT min(IN_DTIME) as in_dtime
		, max(OUT_DTIME) as out_dtime
		, min(WORKINGDAY) as workingDay
		FROM COMMUTE WHERE EMP_NO='ATO_22' AND WORKINGDAY
		BETWEEN '2024-01-15' AND TO_DATE ('2024-01-21')+1 ORDER BY WORKINGDAY;
;
SELECT TO_DATE ('2024-01-21')+1 FROM dual;

INSERT INTO COMMUTE VALUES(COMMUTE_SEQ.NEXTVAL, '2024-01-15', NULL, NULL, '10',0,DEFAULT,'ATO_3',0);
INSERT INTO COMMUTE VALUES(COMMUTE_SEQ.NEXTVAL, NULL, '2024-01-15', NULL, '20',0,DEFAULT,'ATO_3',0);
	

		
